### ISSUE TITLE
请问每次成功运行job但是只展Check_value: False 是什么原因导致啊（没成功打卡）

### ISSUE THREAD

**Issue by brucetby** [Limour-dev/daily_fudan_actions#3]
<img width="348" alt="image" src="https://user-images.githubusercontent.com/100843934/189483731-5835fc04-6308-49e0-8278-2f3371e46009.png">

**Comment by Limour-dev** [comment]
secrets的参数配置完整正确吗？Check_value这个是一个保留的参数，留给看过代码的同学用来解除强制修改为在校状态的。

**Comment by Limour-dev** [comment]
或许可以git pull一下

https://github.com/Limour-dev/daily_fudan_core.git

，然后本地执行一下，看看是报错信息。已经执行了dailyFudan.py，理论上应该会输出报错信息的，这个直接崩溃退出没有其他输出有点奇怪。可能是密码里有啥特殊字符？如果有特殊字符可以看这个issue：

https://github.com/Limour-dev/daily_fudan_core/issues/1

**Comment by brucetby** [comment]
好的谢谢您，我拉到本地调试看看
